### ISSUE TITLE
I noticed a wrong error when interpreting the glossary e.g. address created an error stating that "add"  was missing in nl_NL a totally different translation. A combined translation is also not noted e.g. "template tags" is translated by Google as "sjabloontags"  where "sjabloon"  is a glossary noun which should be "template"

### ISSUE THREAD

**Issue by vibgyj** [vibgyj/WPTranslationFiller#10]

**Comment by psmits1567** [comment]
When retesting it still kept telling me that template was missing, also the color of the bar was not changing
After I added the code below to contentScript the color changed to yellow
function match
case 'nl' :	
	return taMatch(gWord, tWord);

The function called within is modifying some Tamil signs, which are not present of course
But then this function returns true and the wrong verb is removed from the list
