### ISSUE TITLE
It would be nice to have the extension for Firefox, Safari, Edge as well.

### ISSUE THREAD

**Issue by vibgyj** [vibgyj/WPTranslationFiller#11]

**Comment by psmits1567** [comment]
Firefox add-on is working but a proper installation and signed would be great

**Comment by vibgyj** [comment]
@psmits1567 At this time Firefox and Chrome extensions should cover most of the users. Shall we create separate issue for Safari and Edge browsers, change this to only Firefox and close once addon available in Firefox addons?

**Comment by psmits1567** [comment]
Yes I agree but currently I do not see how to alter the title, that is because your are the owner I guess

**Comment by psmits1567** [comment]
Extension in Firefox now working

**Comment by vibgyj** [comment]
Firefox addon has been approved and available for download.
