### ISSUE TITLE
Themes or plugins do have a large description line, which is not translated completely. The translation box is not enlarged to fit the translation, I think the translation may have a buffer/string length issue

### ISSUE THREAD

**Issue by vibgyj** [vibgyj/WPTranslationFiller#13]
![image](https://user-images.githubusercontent.com/27017502/107728653-a30b2480-6cbc-11eb-9a40-b1094b92fb55.png)

**Comment by vibgyj** [comment]
@psmits1567 I think it's fully translated but the text box didn't transform to show everything. After Google translation is applied try clicking inside the text area and make a small change like a space or punctuation. See if the textbox show the rest of the translation.

**Comment by psmits1567** [comment]
@vibgyj Tested your suggestion and indeed if you enter a value the rest of the text shows up.
But that is a bit uncomfortable

**Comment by psmits1567** [comment]
@vibgyj Issue fixed in branch five
