### ISSUE TITLE
Default Formal is used when translating

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#14]
If the extension translates, it gets the formal translation back. This is a bit annoying as the sentence is not correct. There are several locales that have a formal translation as well.
There is no official toggle to change this, however there is a solution obviously, as with deepl.com there is a toggle to change this 
The solution is not that difficult, example below.
Sentence: You are a nice person
Translated: U bent een aardig persoon
Change the "You" into "Je" which is informal
Translation: Je bent een aardig persoon
Notice the change in the first two verbs
Germany has formal
Belgium has formal
This is obviously a new feature, but important to have. When implementing it should be possible to set the verb to trigger this as a param, or there must be an official toggle to switch it. When translating you need to set this in the project to switch to formal

**Comment by psmits1567** [comment]
I have tested this by replacing the formal "You" into the Dutch "Je", then you will get the standard translation instead of Formal
original= original.replace('You','Je');
original= original.replace('you','je');
I propose to make this an option where you can add those words depending on locale, with a toggle to switch it on or off

**Comment by psmits1567** [comment]
@vibgyj enhancement is ready in my Branch, tested and works (not always 100%, need to investigate it more)
Now there is a prereplacement table

**Comment by psmits1567** [comment]
@vibgyj issue is resolved by version v0.9.1
Remark the replacement does not always work for Dutch
With Deepl translation it can be set in params to translate informal

**Comment by vibgyj** [comment]
@psmits1567 Can we close this based on v0.9.2?

**Comment by psmits1567** [comment]
@vibgyj Yes we can close this one

**Comment by vibgyj** [comment]
Thank you @psmits1567
