### ISSUE TITLE
Make it possible to upload multiple glossaries and make it able to choose between them.

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#142]
I help in translating nl_NL, nl_BE and nl_NL-formal.

But, nl_NL(-formal) & nl_BE have various differences in the glossaries... But, to make sure that I have the right glossary active in the right locale. 

So, I think it could be helpful it either hooks into the translation like GlotDict or WPGT tools ... or you are able to upload more then one glossary and have an option to choose between them. It would help a ton instead of having to upload a CSV everytime.

**Comment by psmits1567** [comment]
This needs design, as the current version does not support it.
You could use a different browser that has the second glossary loaded

**Comment by psmits1567** [comment]
Investigation revealed that it would slow down the translation process to much, with the current method. Also there is a risk that we get a memory problem. To solve it properly the glossary should be stored into the database, which causes a schema change. Which in turn causes an update issue.
This is to much for the minor effort it takes to load the glossary for different project.
So for now it will not be implemented
