### ISSUE TITLE
Part sticking out when looking at a waiting string

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#146]
![image](https://user-images.githubusercontent.com/4569581/136654562-f2608645-9f8c-4844-a1c8-defdc7b02f6a.png)

When looking at a waiting see, the column header sticks out at the right (the one of the buttons at the right)

**Comment by psmits1567** [comment]
And which version of WP translation Filler are you using?

**Comment by NekoJonez** [comment]
I used the latest from the releases page, the link from the readme page.
https://github.com/vibgyj/WPTranslationFiller/releases

With WPGPT you mean Vlad's tool?

**Comment by psmits1567** [comment]
What browser are you using, because with chrome I cannot reproduce it.
Also tested without any other extensions active, or with GlotDict and WPGP active

**Comment by psmits1567** [comment]
It is a GlotDict issue in my opinion, you did not show the full list in the  picture, otherwise I would have seen that the GlotDict column is outside his column with the next waiting string. If only WP Translation Filler and WPGP are active, then there is no problem.

**Comment by psmits1567** [comment]
With GlotDict active there is an extra <th> at the end of the line, but it has no class in it.
So this will be shown unformatted!

**Comment by psmits1567** [comment]
Fixed in Branch bug_fixing

**Comment by NekoJonez** [comment]
I'm going to close this one, since I just test it on Opera even with Vlad's tool active and it's looking fine with the bug_fixing one :)
