### ISSUE TITLE
Translation does not handle newline "\n"

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#15]
If a text contains "\n", than this is not handled, the "\n" is removed
![afbeelding](https://user-images.githubusercontent.com/28138634/107849926-a4dd0100-6dfe-11eb-90cf-7e26bf456af6.png)

**Comment by vibgyj** [comment]
May be we can add a placeholder like [1] before sending to Google API and once the translation is back, we can replace it back to newline. Or we can add <br> and send translation as html and get the response and replace <br> back to newline.

**Comment by psmits1567** [comment]
I think your suggestion is worth implementing, but I would not sent it as html for now
Let us stabilize the current method first.
My change does work with the placeholders and "notranslate", but I do not know if that is going to work with the current method

**Comment by psmits1567** [comment]
This problem has been fixed in version _7
