### ISSUE TITLE
Extension error in Opera

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#159]
I can't tell you exactly what triggered it... But, I was helping Vladt test something in his tool and noticed that next to the WPTranslationFiller... There was a "Errors" button and here is what it says: 

![image](https://user-images.githubusercontent.com/4569581/140375335-54c56216-d74c-4df1-8c91-22b54a36bd6f.png)

**Comment by psmits1567** [comment]
Thanks for reporting the issue, however it is a known message. It has noting to due with Opera. It happens when you reload the page once you are within a translation page.

**Comment by psmits1567** [comment]
The error is not longer shown, but it needs further improvement. Sometimes the history is not shown

**Comment by psmits1567** [comment]
Added an extra check for &historypage, which is added by WPGPT or GD.
If that is present do not show the label for old records. Triggering this was causing the error message after a reset of the add-on
