### ISSUE TITLE
Translated strings "vanish"

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#160]
I can't tell exactly when this happen but when I edit a string/save one... Sometimes one of the strings next to it doesn't show up until I open/close the string I edited/saved or another string. Possibly related to #159 ? Or issue that I'm not using Chrome but Opera?

**Comment by psmits1567** [comment]
Which version are you currently using ?
I have the impression that this is caused by a slow internet connection.
Could you test the same with Chrome to see if it there also happens?
Until now with the current version "security" I do not have this problem with Chrome

**Comment by NekoJonez** [comment]
I use the latest stable release on Opera. 
I tried to clean the cache and it seems to happen WAY less frequently now. 

I would highly doubt that it's slow internet, since it also happens on a device that has a wired connection and my connection is stable and reaches high speeds. 
I don't think this is "slow internet" :P 
![image](https://user-images.githubusercontent.com/4569581/140485903-96e7e25b-1a8a-4bb7-b488-2b2aa076892a.png)

But, I can totally see where you are coming from. I'll test it on my work computer next week... There I have not only a weaker WiFi chipset but there a WAY more traffic on the network during school and ideal way to test it.

**Comment by NekoJonez** [comment]
I use the latest stable release on Opera. 
I tried to clean the cache and it seems to happen WAY less frequently now. 

I would highly doubt that it's slow internet, since it also happens on a device that has a wired connection and my connection is stable and reaches high speeds. 
![image](https://user-images.githubusercontent.com/4569581/140486072-35807cbb-59b8-4586-8143-6ecc3896194c.png)



But, I can totally see where you are coming from. I'll test it on my work computer next week... There I have not only a weaker WiFi chipset but there a WAY more traffic on the network during school and ideal way to test it.

**Comment by NekoJonez** [comment]
So @psmits1567 , some further testing... On the latest version of Opera with the current stable release.

Quite often, strings "vanish" when using this tool.

How I can reproduce it, is when I submit a string, the one underneath is goes "poof". But, when I open another string or refresh the page, it appears again. 

Shall I test with another build of the tool on Opera or see if this also happens on other browsers? What's the first thing I should test?

**Comment by psmits1567** [comment]
When using Chrome I do not see this behavior.
So please check with security version and Chrome
You could also check what happens when TF is not activated.

**Comment by psmits1567** [comment]
Which save are you using? The button in the prio column, or the button in the editor

**Comment by NekoJonez** [comment]
So, I use the master one. 

This is what happens on Opera: https://youtu.be/_hQQ3AS_Wrk
It also happens when I disable GlotDict & WPGP tools. 
It also happens when I clean my cache and such.

**Comment by NekoJonez** [comment]
![image](https://user-images.githubusercontent.com/4569581/141642375-9a9e3290-5ae8-4d98-a20a-446022dd7113.png)

With master in Chrome ... Same issue.

This is what Opera is saying: 

![image](https://user-images.githubusercontent.com/4569581/141642439-e73421fb-441b-4896-80df-e51551562292.png)

**Comment by NekoJonez** [comment]
As suggested on Slack by @psmits1567 , this is an issue that's fixed in other dev branches. I just tried security branch and it doesn't happen on Opera nor Chrome. :) So, yeah... It's a problem with the current master version.

**Comment by psmits1567** [comment]
Thanks for testing it again.
But question about the first image, because WP translation Filler does not use bundle.min.js!
This must be some other add-on activated which uses this js script
Neither does it use JQuery, or core.min.js

**Comment by NekoJonez** [comment]
Well, I disabled all other translate.wp.org plugins. The only other add-ons I have running is Ghostery, LanguageTools, Honey, and a ColorPicker tool that tells me exactly what the RGB code of a pixel is. 
But, I wouldn't stress too much over it. Since it's fixed in security branch.
