### ISSUE TITLE
"/" blocks/mess up the checking.

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#185]
In nl_BE we use "aan-/uitzetten" for "toggle". I notice that WPTransFill sees it as used when you only write "aan-/" or "/uitzetten". 
I think the "/" is doing some funky stuff with the check code.

**Comment by NekoJonez** [comment]
![image](https://user-images.githubusercontent.com/4569581/153644043-bfbfa7d4-c241-41f2-86a5-249d1c409472.png)

As you can see, WPTransfill colors green and I haven't fully written out "aan-/uitzetten"

**Comment by psmits1567** [comment]
Which glossary are you using?

**Comment by NekoJonez** [comment]
nl_BE of course ;) 
https://translate.wordpress.org/locale/nl-be/default/glossary/

**Comment by psmits1567** [comment]
Reproduced, it is not the /but the "-" sign that causes this problem, but the combination of -/
It is caused by this routine
 let key = entry[0].replaceAll("\"", "").trim().toLowerCase();
                let value = entry[1].split("/");
                for (let val in value) {
                    if (value != ""){
                       value[val] = value[val].replaceAll("\"", "").trim();
                    }
                }

replacing the "/" with "," seems to solve this issue
The separator in the nl_NL and nl_BE glossary is "," not "/"

The "\" is used to split the value
I need to discuss this with vibgyj, why this function is present

**Comment by psmits1567** [comment]
This function was designed to handle glossary lines like below
select, selecteer/selecteren which is a glossary design to be able to indicate more then one word.
If this construction is present, then it is not handled properly.
So in the example given by @NekoJonez, the "/" was removed and the verb was split into an array and shown as "aan,uitzetten"
This is now prevented by checking on "-/", if that is present than the string is not split.
Also the routine for checking the glossary handled separate characters to compare.
That causes the bar to be green if just one single character was found regardless if the second letter is wrong
This now has been changed, it looks for the value entered and compares that against the glossary verbs present
