### ISSUE TITLE
JavaScript error for button "translate"

### ISSUE THREAD

**Issue by CWBudde** [vibgyj/WPTranslationFiller#218]
I haven't had time for a close check, but hitting "translate" causes an issue on the console:

commonTranslate.js:966 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'length')
    at translateEntry (commonTranslate.js:966:32)
    at contentScript.js:710:13

If time permits, I'll add this report with more details later...

**Comment by psmits1567** [comment]
Did you load the glossary, from within the options? If so how much entries are within it.

Or did you add pretrans and posttrans verbs?
Take care that there is no blank line at the end

**Comment by psmits1567** [comment]
Which branch did you download?
The start 710 in contentscript has nothing to do with translation. That has to do with importing a previously exported local database

**Comment by CWBudde** [comment]
Thanks for the quick reply. It seems the configuration has not been stored properly and that the firewall has blocked some access. I'll review this in detail this evening
