### ISSUE TITLE
If a translation contains the following placeholders &gt; and &amp; they will get a blank after the &

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#22]
If a translation contains the following placeholders &gt; and &amp;, then the will also get a blank behind the & character
So &g;t becomes & gt; and &amp becomes & amp;

**Comment by vibgyj** [comment]
@psmits1567 This issue is fixed by placeholder fix we're doing. Shall I mark it for next milestone as that contains the placeholder fix?

**Comment by psmits1567** [comment]
@vibgyj yes that is ok, it will testing to confirm the placeholders are now handled properly

**Comment by psmits1567** [comment]
@vibgyj issue is resolved by version v0.9.1

**Comment by psmits1567** [comment]
@vibgyj issue is resolved by version v0.9.2
