### ISSUE TITLE
Error in file reader

### ISSUE THREAD

**Issue by CWBudde** [vibgyj/WPTranslationFiller#220]
Looking at the console, I found this error message

```
Uncaught TypeError: Failed to execute 'readAsText' on 'FileReader': parameter 1 is not of type 'Blob'.
    at HTMLInputElement.<anonymous> (options.js:372:12)
```

I'm not sure where it originates from, especially since the source code does not look wrong. The only thing I could imagine is the fact that no file is passed. This can be solved by adding a check for

```
if (this.files.length == 0) {
    return
}
```

before any further processing.

And btw. assuming a locale of "nl" does not look good here. I guess it's a left-over that can easily just be removed.

**Comment by psmits1567** [comment]
Hi, apologies for the late reply, I did not get a notice of this issue
I will have a look at your problem, and indeed assuming "nl" is not OK
Can you indicate which version your were using ?
What OS are you using ?
Currently I cannot reproduce this, but I will add your fix into the latest version
and locale = "nl" is a left over
