### ISSUE TITLE
Fuzzy & reject coloring the strings wrong - visual bug

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#231]
Used: 

WPTransfill v1.6.14
GlotDict 2.0.9
Opera 89.0.4447.83

Also enabled & active on the translate.wp.org page: Ghostery v8.7.4 (set to **unactive** on Translate.wp.org), LanguageTool v, Eye Dropper v0.5.14, WPGP v2.1.0 

Important note, I also always tested with cache & such cleaned AND with and without all other browser extensions disabled/enabled. The results didn't change.

When WPTransfill is enabled, the colors of GlotDict appear wrong when you use the quick action buttons at the side. They always appear green when you select fuzzy or reject. 

See in this video:

https://youtu.be/7i7OF4kWMLM

This is **only a visual bug**! Since the action preformed is correct. As you can see when the page refreshes. 

@psmits1567 already informed me that this WPTransfill version might not be the latest since a new version is uploaded to Google Store but still in approval process. When I notice that this new version is in my browser and the problem changes or fixes itself, I'll add that info to this ticket.

**Comment by NekoJonez** [comment]
I changed the title, since I notice this behaviour happening when GlotDict is enabled and you also use the "reject" and "fuzzy" buttons in the string edit section. (Those underneath the "give feedback" section)

**Comment by psmits1567** [comment]
What happens if you reject the string with GlotPress not GlotDict??
And what is the status of the record after you do this??

**Comment by psmits1567** [comment]
Reproduced, but WPTF without GlotDict is working fine, so I suggest that the GlotDict team has a look at it

**Comment by psmits1567** [comment]
If you have all active, and you reject from within the record, then the color is correct. So this is in my opinion something that GlotDict has to investigate.

**Comment by NekoJonez** [comment]
Strange thing is, when GlotDict is active and not WPTF, the right color shows.... But I will let them know.

**Comment by psmits1567** [comment]
It is a CSS issue as far as I can see now. Because when WPtranslation filler is active without GlotDict, the color is OK
If you reject from within GlotPress the color is also OK.
If you reject without GlotDict the color is also OK,so maybe the prio is set wrong in GlotDict

**Comment by NekoJonez** [comment]
I think so too. I think you might be correct that when GlotDict and WPTF are both active, one takes prior and the wrong color is chosen from css.

**Comment by psmits1567** [comment]
Investigating the color setting after rejecting with GlotDict active, I see the following in debug mode
element.style {
    background-color: rgb(181, 225, 185);
}
If I toggle that out, the color is OK
In WPTF I only have this setting for translation OK
table.translations tr.preview.wptf-translated {
    background-color: #FFFFC2;
}
So I suspect that GlotPress overrules the GlotDict setting due to the status of the record.
If you reject with GlotDict there is no indication it is done by GLotDict

**Comment by NekoJonez** [comment]
> After adding the rejected status in our CSS it is still overruled by GlotPress I think
> After making it important in WTTP it gives the proper color.
> But I still think this is something GlotDict needs to check
> Add this into the CCS from WPTF, and you can see that it shows the proper color
> 
> table.translations tr.preview.status-rejected {
>     background-color: #eb9090 !important;
> }

And then the orange for fuzzy with the right color code & instead of rejected put fuzzy.

**Comment by psmits1567** [comment]
For fuzzy add this code to the css of WPTF
table.translations tr.preview.status-fuzzy {
    background-color: #f6a983 !important;
}

**Comment by vlad-timotei** [comment]
Looks like you found the issue here. Since the order of the CSS injected by different extensions cannot be determined beforehand, you can use the solution above (`!important`) to make WPTF compatible with GlotDict. :)

**Comment by psmits1567** [comment]
It is GlotDict not behaving properly, and as WPTF is obviously the last one activated I make it work. But honestly I have the opinion GlotDict needs to fix this. I have this added into my current development version, so it works as it is supposed to do. The next version of WPTF is not planned soon.

**Comment by NekoJonez** [comment]
I added the CSS code:

`table.translations tr.preview.status-rejected {
background-color: #eb9090 !important;
}

table.translations tr.preview.status-fuzzy {
background-color: #f6a983 !important;
}`

To WPTF and it didn't work. I added it to GlotDict and it works fine now :)

**Comment by psmits1567** [comment]
I added this to the the latest build, and there it worked fine. But as stated before, this is a GlotDict issue

**Comment by psmits1567** [comment]
What do you mean by adding this comment?
Also which version are you currently using?
The official version is way behind currently

**Comment by NekoJonez** [comment]
> What do you mean by adding this comment? Also which version are you currently using? The official version is way behind currently

Since, this is something that is still an issue when either GlotDict OR WPTransFill updates... Currently running v1.6.14 of TransFill & GlotDict 2.1.1

**Comment by vlad-timotei** [comment]
Reposting this here. 

IMHO GlotDict shouldn't add code to be compatible with other extensions when those update. It is not sustainable. Its main purpose is to be compatible with GlotPress on w.org and as a main extension, other extensions should ensure compatibility with GlotDict. 

I don't see why the css can't be added in wptf if it is only needed when wptf is present. 😁

**Comment by psmits1567** [comment]
Please update to spellcheck branch, as already indicated you are working with an old version of WPTF. Then rechecknif the issue is stil present

**Comment by psmits1567** [comment]
I have retested this again, but do not see the problem
Retested with GlotDict 2.1.1 and WP Translation Filler 2.01 "spellcheck" branch
So again please test it with those two version again
Let me know if you still have problems with the colors

**Comment by psmits1567** [comment]
![image](https://user-images.githubusercontent.com/28138634/231534808-57a0f2c0-edbc-4512-980f-f0e6f4f256c5.png)
Proof of proper colors no green color when rejecting
