### ISSUE TITLE
Expand the info on the glossary CSV in the options page

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#234]
Since glossaries tend to change from time to time, it would be handy if we could check if the glossary uploaded is the latest version. 

I think it would be handy if you would be able to see an upload date. Since then, you could check e.g. Slack logs when something changed in the glossary. Also, when you see that date you could also know if you have uploaded the latest version or not.

**Comment by psmits1567** [comment]
If you use the latest official version it should show the upload date below the name of the glossary.
Is this not shown currently, or are you not using the latest release?

**Comment by NekoJonez** [comment]
I'm using v1.6.14. The one of the Chrome store.

**Comment by NekoJonez** [comment]
I notice the date now, but I'd add that underneath with a label. Just to make it that more clear.

**Comment by psmits1567** [comment]
That is a design whish, I would like to have the screen as small as possible to prevent unnessesary scrolling. The upload date is shown
It would be better to open a ticket on translate.wordpress.org to add a version into the glossary. The version should be maintained by the team. That makes it more obvious which version you are using

**Comment by psmits1567** [comment]
As it is already separated from the filename, I do'nt want to add another field for it
