### ISSUE TITLE
Add a "previous" button to the options page.

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#235]
Since there is now a button added to the menu bar on translate.wp.org, it'd be more UX friendly if there is a back button on the options page. 

GlotDict option page is a dropdown and WPGP has a "close options" which brings you back. WPTF has nothing really of the sorts. 
Granted, you can click on the return button in your browser, but I think it would help with accessibility to have a return button in the options page itself.

**Comment by psmits1567** [comment]
Added a button to the options screen below the title in the latest build

**Comment by psmits1567** [comment]
Fixed in version 3.0.3
