### ISSUE TITLE
If a translation has been saved with an error, and you reopen this translation the colored bar is not shown

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#24]
If you translate manually without the button "Translate" it will show a colored bar if there is a word not properly translated as is in the glossary. If you save such a translation and reopen the translation, I would expect the colored bar to popup again, as the translation contains a word that is not ok according the glossary
![afbeelding](https://user-images.githubusercontent.com/28138634/107937257-fa8ee600-6f83-11eb-968e-e118865261dc.png)
Here the word "pagina's" is the same as within the glossary, so either a green bar should be shown, or the colored bar indicating the error as it previously stated "pagina&#39;s"

**Comment by vibgyj** [comment]
@psmits1567 When check the already translated strings the extension changes the color of the bar if there's any error or all words found in the glossary have the right translation. The color of the bar doesn't change when none of the words in the original are not found in the glossary. Can you give a link to an example of this issue to troubleshoot?

**Comment by psmits1567** [comment]
The problem is that the addTranslateButtons() function is not added when you do this
https://translate.wordpress.org/projects/wp-plugins/ecommerce-product-catalog/stable/nl/default/?filters%5Boriginal_id%5D=10407522
With this you can test it

**Comment by psmits1567** [comment]
@vibgyj it seems that under this condition the listener is not started, because if you type then the bar is also not shown/changing

**Comment by psmits1567** [comment]
@vibgyj I propose that we close this issue, as it is working with the latest version due to my fix for the translate button within the edit screen
