### ISSUE TITLE
Placeholder not correctly improved

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#26]
Google messes up the placeholders by adding spaces. To convert it back to the original the spaces need to be removed. This has partially been fixed, but in the following situation it does not work
Original line contains:
an %1$soutdated
Translated into locale nl_NL:
 een% 1 $ verouderde

The blanks are not removed, and the "s" character is missing
Test line in wordpress.org
https://translate.wordpress.org/projects/wp-plugins/all-in-one-seo-pack/dev/nl/default/?filters%5Boriginal_id%5D=10991311

**Comment by vibgyj** [comment]
@psmits1567 If this is a new type of placeholder, we can add it to the regex filter. I'll take a look at it.

**Comment by psmits1567** [comment]
@vibgyj I need to retest this one as it was probably caused by the regex we changed. After that I did not see it anymore

**Comment by psmits1567** [comment]
Restested this issue and is fixed by my last solution
