### ISSUE TITLE
After succesfully uploading a (newer) glossary, the options page should refresh to show the newly uploaded glossary.

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#263]
It's a **minor** UX thing, but when you succesfully uploaded a glossary .... only a refresh or re-opening of the options page shows that you succesfully uploaded. If the page refreshes after a succesful upload and pressing the "OK" button, this won't be a problem.

**Comment by psmits1567** [comment]
A refresh only makes sense after clicking the save button, otherwise you would loose other configuration changes. As they were not saved at that time.

**Comment by psmits1567** [comment]
Pieterjan I have fixed this by updating the field after uploading. But currently it shows the date when you uploaded the file, so not the date from the file itself! I have not altered this behavior, but I can imagine that it would make more sense if the date of the uploaded file is shown
