### ISSUE TITLE
Currently the addon notifies if a translation misses a glossary verb, but it would be great if a list of verbs could be defined to replace them

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#29]
in the current version a warning is shown when a glossary word is not present within the translation.
That is a great functionality, but it would save time if you could also define a list of verbs that automatically are replaced.
Because not all lines in the glossary can be used for that purpose depending on the translation
But there are some verbs/nouns that can be replaced independent of the translation
Example in the nl_NL glossary we have "website"  which should be translated as "site"
This is a verb that is very often used, so instead of the warning it can be replaced automatically
This would again save time

**Comment by vibgyj** [comment]
@psmits1567 I think this is coming out in the current changes. I'm marking this for next milestone. Please let me know if it's a different issue.

**Comment by psmits1567** [comment]
@vibgyj yes this one can be fixed by the new function to replace verbs

**Comment by psmits1567** [comment]
As the new version of 27-02-2021 has this functionality which works, this issue can be closed
