### ISSUE TITLE
Glossary issue with spaces

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#296]
So, in nl_BE... Site icon --> Favicon. I added it like that in the glossary.
Yet, Transfill says no to that since the space. It says that it's wrong since the missing verb is Site -> Website.

(Removed the screenshot since that pop up didn't show up)

**Comment by psmits1567** [comment]
This is due to the fact that it are two different glossary entries, so it cannot be treated as one
