### ISSUE TITLE
Improvement in wording in "Don't save this string!!!"

### ISSUE THREAD

**Issue by NekoJonez** [vibgyj/WPTranslationFiller#297]
Currently, it ALWAYS says that you have "missing verbs". Yet, what if it's only nouns? 
Maybe that "Verb" needs to be a variable that gets if it's a noun, verb, etc ... and show that?

**Comment by psmits1567** [comment]
I will change the text, as it is difficult to split this into separate situations! So will make it "missing verbs/nouns"

**Comment by NekoJonez** [comment]
Or just missing... Since then somebody can come and argue about all other things Glotpress adds like interjections

**Comment by NekoJonez** [comment]
Thats perfect and to the point, no discussion possible. :)

**Comment by psmits1567** [comment]
Fixed in version OpenAI branch
