### ISSUE TITLE
Make translation list wider

### ISSUE THREAD

**Issue by toineenzo** [vibgyj/WPTranslationFiller#331]
When I enable the plugin, I notice the translations list on translate.wp.org gets less wider. I noticed the following code:
https://github.com/vibgyj/WPTranslationFiller/blob/3e2b5427dc335eeefa69d2cbec0fab9dd0aefb05/src/wptf-style.css#L3

Can't this be changed to something better, like 90%? This will make it much easier to work on translating long strings.

**Comment by psmits1567** [comment]
No I don't want to make it wider, as it makes the it less readable.
