### ISSUE TITLE
Due to the unwanted behavior of Google translate, you will end up with wrong placeholders e.g. % 1 $ s. It would be great if this could be fixed during translation. 

### ISSUE THREAD

**Issue by vibgyj** [vibgyj/WPTranslationFiller#4]
This would need implementation of a new table containing those wrong placeholders, like the glossary table. Or maybe a regex function that could do that.

**Comment by vibgyj** [comment]
Fixed in release [v0.6](https://github.com/vibgyj/WPTranslationFiller/releases/tag/v0.6)

**Comment by psmits1567** [comment]
Tested the new version, unfortunately now blanks or not removed behind the placeholder, or are remove before the placeholder where they should stay.
Some examples with new version, blank behind is not removed.
Houd er rekening mee dat de huidige <em**>%s <**/em> -module is verouderd en zal worden verwijderd in toekomstige updates. Gebruik in plaats daarvan de module <em**>%s <**/em>.Here the blank is removed, which in this case is wrong
Ga na het instellen van het aantal **naar%s** om elke gateway-optie in te stellen.
It should be
Ga na het instellen van het aantal **naar %s om** elke gateway-optie in te stellen.Products <strong>%from% - %to%</strong> from <strong>%total%</strong>. Products on page %select_form%
Blank not removed behind
Producten <strong>**% van**% -% tot% </strong> van <strong>% total% </strong>. Producten op pagina%select_form%Here the last % is missing original  :Use %s variable for product's base price. For example: %s.
Gebruik de variabele %s voor de basisprijs van het product. Bijvoorbeeld:Here it is removed where it should not be removed
Hello %1$s (not %1$s? <a href="%2$s">Log out</a>)
**Hallo%1$s** (niet%1$s? <a href="%2$s"> Uitloggen </a>)So generally no more spaces within the placeholder, but now the spaces are removed where they should stay. And spaces behind are not removed. It is improved but not 100%
