### ISSUE TITLE
With the translate button in the line itself, the colored bar is not changing color

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#40]
Before adding the button within the translation line the bar changed from color if you corrected the translated line.
That does no longer change color, if red it stays red

**Comment by vibgyj** [comment]
@psmits1567 I see that the bar color is still changing. Can you please check if the issue is still there? If so, please give an example link so that I can troubleshoot.

**Comment by psmits1567** [comment]
@vibgyj here is an example
https://translate.wordpress.org/projects/wp-plugins/custom-registration-form-builder-with-submission-manager/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6099438&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc
It appears to me that with the latest official version, the fact that you alter the text is not recognized. It keeps indicating the same glossary verbs to be wrong

**Comment by psmits1567** [comment]
Another example where the color should be red and showing the verbs that are not ok
![afbeelding](https://user-images.githubusercontent.com/28138634/109294167-208e7300-782d-11eb-99c4-f9d0729a36b8.png)

**Comment by psmits1567** [comment]
https://translate.wordpress.org/projects/wp-plugins/custom-registration-form-builder-with-submission-manager/stable/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=6099438&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc
![afbeelding](https://user-images.githubusercontent.com/28138634/109295017-52eca000-782e-11eb-89c6-ff97f09f80bc.png)
After changing the word "placeholder"  you see the debug information coming for the calculation, but the array containing the wrong words seems not to be updated
![afbeelding](https://user-images.githubusercontent.com/28138634/109295257-b70f6400-782e-11eb-8f95-d72e897e6823.png)

**Comment by psmits1567** [comment]
Found the problem within contentScript.js, the match instruction was incorrect
Before my change it does not work :match(language, gWord, translation
let isFound = false;
                for (let gWord of gItemValue) {
                    if (match(language, gWord, translation)) {
                        console.log('+ Translation found:', gWord);
                        isFound = true;
                        break;
                    }
                }
After correction :translation.match(gWord))
for (let gWord of gItemValue) {
					console.log('word to find',gWord);
                    if (translation.match(gWord)) {
                        console.log('+ Translation found:', gWord);
                        isFound = true;
                        break;
                    }
                }

**Comment by psmits1567** [comment]
@vibgyj This must have something to do with missing parameters.
I have reverted my change, because I thought that "match" was a javascript statement!
But it appears that it is a function in ContentScript.
What should happen if I add "nl" in this function?

But should you not alter the name of the function as it is normally a javascript command ?
I think this one can be closed, as it is now working

**Comment by vibgyj** [comment]
@psmits1567 I briefly checked this issue and it seems like the already translated blocks have different kind of id like **editor-2379367-63598954** vs untranslated blocks have like **editor-2379367**. The element search isn't handling this case.

**Comment by psmits1567** [comment]
@vibgyj issue resolved with version v0.9.1

**Comment by psmits1567** [comment]
@vibgyj issue resolved with version v0.9.2
