### ISSUE TITLE
Duplicate placeholders

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#41]
There is a problem with replacing the placeholders. Sometimes you get a <strong>double </strong>Font-size adjustment in more places:</strong> now, font-size controls are right where you need them in the List and Code blocks. No more trekking to another screen to make that single change!
Translated
<strong>Aanpassing van </strong>lettergrootte <strong>op meer plaatsen:</strong> nu zijn de besturingselementen voor lettergrootte precies daar waar u ze nodig hebt in de lijst- en codeblokken. U hoeft niet meer naar een ander scherm te trekken om die ene wijziging aan te brengen!
It depends on the length of the sentence in my opinion

**Comment by psmits1567** [comment]
This is an example where it works fine
<strong>Reusable blocks:</strong> several enhancements make reusable blocks more stable and easier to use. And now they save automatically with the post when you click the Update button.

<strong>Herbruikbare blokken:</strong> verschillende verbeteringen maken herbruikbare blokken stabieler en gemakkelijker te gebruiken. En nu slaan ze automatisch op met het bericht wanneer u op de knop Update klikt.

**Comment by vibgyj** [comment]
@psmits1567 I don't understand this issue. Can you please give an example link to troubleshoot?

**Comment by psmits1567** [comment]
I can understand why you not see it, have a look at the difference between original and translation
The translation has to many bold verbs because the tag "strong"  and "/strong" are double
Here is the original line
https://translate.wordpress.org/projects/wp/dev/admin/nl/default/?filters%5Bstatus%5D=either&filters%5Boriginal_id%5D=11354325&sort%5Bby%5D=translation_date_added&sort%5Bhow%5D=asc

**Comment by psmits1567** [comment]
@vibgyj Put this one on hold, because with my current version it does not happen anymore
This has probably been caused by using the <span> "notranslate"  </span> manner to prevent blanks in translations
Now with the method of [1] it does not seem to happen.
After the milestone this needs testing again

**Comment by psmits1567** [comment]
Cannot reproduce it with the release from 28-02-2012
