### ISSUE TITLE
In extension settings, if you enter the parameters, then the screen is not refreshed, so you do not know if saving has worked.

### ISSUE THREAD

**Issue by vibgyj** [vibgyj/WPTranslationFiller#5]

**Comment by psmits1567** [comment]
This issue has been resolved, as you now get a popup
But the save button is a bit to far to the right e.g. not properly aligned
![afbeelding](https://user-images.githubusercontent.com/28138634/108116591-18e80500-709c-11eb-95ea-e5750577182e.png)

**Comment by psmits1567** [comment]
This issue can be closed

**Comment by vibgyj** [comment]
Thank you @psmits1567 Closing the issue.
