### ISSUE TITLE
If the %d is not a placeholder, but part of a verb, than it is still converted to a placeholder, causing a blank to be left behind

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#52]
Sometimes %d is not a placeholder, but it is a preceded by a % sign, so it should not be treated as a placeholder for %d
Test example:
https://translate.wordpress.org/projects/wp-plugins/woocommerce-jetpack/stable/nl/default/?filters%5Boriginal_id%5D=5659716
Original contains:
%product_title% is not available until %direct_date%.
Translation contains:
% product_title% is niet beschikbaar tot %d irect_date%.

**Comment by psmits1567** [comment]
@vibgyj is resolved with new regex added to version v0.9.1

**Comment by vibgyj** [comment]
Not fixed in v0.9.2, need to check regex.

**Comment by psmits1567** [comment]
Is working in the current version 3.0.3
