### ISSUE TITLE
If a page does not have translations on the left side you will get RED flags because it does not find the glossary verbs

### ISSUE THREAD

**Issue by psmits1567** [vibgyj/WPTranslationFiller#58]
If a translation line is empty it gets RED flagged due to the fact that it is not finding the glossary verbs.
This seems a bit strange to check for glossary verbs if the line is empty.
I think it would be nicer to not check the glossary if the line is empty, just only check it if there is a translation present

**Comment by psmits1567** [comment]
@vibgyj Fixed this in my current Branch

**Comment by vibgyj** [comment]
@psmits1567 Can this be closed based on v0.9.2?

**Comment by psmits1567** [comment]
@vibgyj Yes it can be closed

**Comment by vibgyj** [comment]
Thank you @psmits1567
