### ISSUE TITLE
In extension settings, if the key is wrong, no error is shown when translating, it simply does not show the translation.

### ISSUE THREAD

**Issue by vibgyj** [vibgyj/WPTranslationFiller#6]
This could be prevented when the API key is checked when saving the settings.

**Comment by psmits1567** [comment]
@vibgyj Another solution is to add a warning if error 400 comes back when the request is sent.
In that way you know something is wrong
Tested with this change in function sendAPIRequest, an alert box is shown with the error
function sendAPIRequest(e, language, apikey, requestBody, original) {
    xhttp = new XMLHttpRequest();
    xhttp.onreadystatechange = function () {
        if (this.readyState == 4 && this.status == 200) {
            let responseObj = JSON.parse(this.responseText);
            let translatedText = responseObj.data.translations[0].translatedText;
            console.debug("Translated text: ", translatedText);

            translatedText = postProcessTranslation(
                original, translatedText, replaceVerb);
            // translatedText = processPlaceholderSpaces(original, translatedText);

            let textareaElem = e.querySelector("textarea.foreign-text");
            textareaElem.innerText = translatedText;
            validateEntry(language, textareaElem);
        }
		else {
			console.log("readyState and status after request",this.readyState,this.status);	
		}
		if ( this.readyState == 4 && this.status == 400){
				alert("error 400 after request API key possibly not OK");	
				return false;
			}
		
    };

**Comment by psmits1567** [comment]
I think with the warning this issue can be closed, as it probably will catch other 400 errors as wel.

**Comment by psmits1567** [comment]
@vibgyj solved with version of 07-03-2021

**Comment by psmits1567** [comment]
@vibgyj Fixed by release v0.9.1

**Comment by psmits1567** [comment]
@vibgyj issue is resolved with version v0.9.2
