### ISSUE TITLE
Google API: space, capital letter, \

### ISSUE THREAD

**Issue by vibgyj** [vibgyj/WPTranslationFiller#8]
If a translation from Google does not start with a capital, but the original does start with a capital, it would be great if that is corrected on the fly. Also if the line should start with a blank, Google removes that, so that should be checked as well. Same for '\' which Google sometimes does not translate.

**Comment by psmits1567** [comment]
@vibgyj issue is resolved by version v0.9.1

**Comment by psmits1567** [comment]
@vibgyj issue is resolved with version v0.9.2
