### ISSUE TITLE
Currently if an error is present a colored bar is shown, which you need to point at it to see the problem. It would be great if the problem is shown in the colored bar directly, which makes it more clear.

### ISSUE THREAD

**Issue by vibgyj** [vibgyj/WPTranslationFiller#9]

**Comment by psmits1567** [comment]
@vibgyj I think now we have the autoreplacement function, that we can close this one. If you are working in the proper flow, then you will first use the autoreplacement function, then there will be practically no missing verbs.

**Comment by psmits1567** [comment]
@vibgyj Alternatively we could implement this pure javascript marker https://markjs.io/

**Comment by psmits1567** [comment]
Missing verbs are now shown within the editor, and in the buttons on the side
